### ISSUE TITLE
Поддержка дополнения

### ISSUE THREAD

**Issue by sergant210** [dobroweb/easyBlacklist#3]
Добрый день!
Планируется ли поддержка данного дополнения? Меня просят выложить мою версию данного компонента в официальный репозиторий. Ты не планируешь это сделать?

**Comment by feschukov** [comment]
Добрый день.
Поддержка планируется. Постараюсь сегодня выложить на GitHub и modstore
обновление. Описание поменяю чуть позднее.

**Comment by feschukov** [comment]
Выложил обновление в [репозиторий modstore.pro](https://modstore.pro/packages/users/easyblacklist)
